# Generated by Django 3.0.7 on 2020-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200610_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='tracks/album.jpg', upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='tracks/music.jpg', upload_to='tracks/'),
        ),
    ]
