# Generated by Django 3.0.7 on 2020-06-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_auto_20200610_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default='tracks/album.jpeg', upload_to='albums/'),
        ),
    ]
